export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const FOLLOW = "FOLLOW";
export const UNFOLLOW = "UNFOLLOW";

export const UPDATE_USER_AVATAR = "UPDATE_USER_AVATAR";
export const UPDATE_USER_AVATAR_FAIL = "UPDATE_USER_AVATAR_FAIL";

export const UPDATE_USER_USERNAME = "UPDATE_USER_USERNAME";
export const UPDATE_USER_USERNAME_FAIL = "UPDATE_USER_USERNAME_FAIL";

export const UPDATE_USER_BIYOGRAFI = "UPDATE_USER_BIYOGRAFI";
export const UPDATE_USER_BIYOGRAFI_FAIL = "UPDATE_USER_BIYOGRAFI_FAIL";

export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD";
export const CHANGE_USER_PASSWORD_FAIL = "CHANGE_USER_PASSWORD_FAIL";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_FAIL = "RESET_PASSWORD_FAIL";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";
